services:
  wtp-lib:
    container_name: wtp-library
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./projects.json:/app/projects.json
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PORT: 3000
      LISTEON_ON: "0.0.0.0"

  tunnel:
    container_name: zoraxy_tunnel # Name of the Cloudflare Tunnel container
    image: cloudflare/cloudflared:latest # Pull the latest version of the Cloudflare Tunnel image
    restart: unless-stopped # Restart the container unless manually stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN} # Pass the Cloudflare Tunnel token from environment variable
    command: tunnel run # Command to start the Cloudflare tunnel
    hostname: cloudflare-tunnel # Hostname for the Cloudflare Tunnel container
